# Generated by Django 6.0.4 on 2026-05-03 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_date', models.DateField()),
                ('city', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('heard_via', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('friend', 'Friend'), ('google', 'Google')], max_length=50)),
                ('package', models.CharField(max_length=150)),
                ('celebration', models.CharField(choices=[('wedding', 'Wedding'), ('pre-wedding', 'Pre-Wedding'), ('save_the_date', 'Save The Date'), ('birthday', 'Birthday'), ('events', 'Events')], max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
