# Generated by Django 6.0.4 on 2026-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
