# Generated by Django 6.0.4 on 2026-05-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_booking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='price_of_package',
        ),
    ]
