# Generated by Django 6.0.4 on 2026-05-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_price_booking_price_of_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
