# Generated by Django 6.0.4 on 2026-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('sessioncompleted', 'Session Completed'), ('editinginprogress', 'Editing in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('customercancelled', 'Customer Cancelled')], default='pending', max_length=50),
        ),
    ]
