# Generated by Django 6.0.4 on 2026-05-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
