# Generated by Django 6.0.4 on 2026-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='media/')),
                ('work_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=50)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('pre-wedding', 'Pre-Wedding'), ('save_tha_date', 'Save-the-date'), ('birthday', 'Birthday'), ('events', 'Events')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Works',
            },
        ),
    ]
