# Generated by Django 6.0.4 on 2026-05-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='file',
            field=models.FileField(upload_to='works/'),
        ),
    ]
