# Generated by Django 6.0.4 on 2026-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_works_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('pre-wedding', 'Pre-Wedding'), ('save_tha_date', 'Save the date'), ('birthday', 'Birthday'), ('events', 'Events')], max_length=50),
        ),
    ]
