# Generated by Django 6.0.4 on 2026-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_works_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
