# Generated by Django 6.0.4 on 2026-05-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_works_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='file',
            field=models.ImageField(upload_to='works/'),
        ),
    ]
